package com.tru.theme

import androidx.compose.ui.graphics.Color

// Primary
val primary_light = Color(0xFFE6E6ED)
val primary_light_hover = Color(0xFFD9D9E3)
val primary_light_active = Color(0xFFB0B0C6)
val primary_normal = Color(0xFF000047)
val primary_normal_hover = Color(0xFF000040)
val primary_normal_active = Color(0xFF000039)
val primary_dark = Color(0xFF000035)
val primary_dark_hover = Color(0xFF00002B)
val primary_dark_active = Color(0xFF000020)
val primary_darker = Color(0xFF000019)


val naturalNormal = Color(0xFF919097)

val successLight = Color(0xFFEDF7ED)

val errorNormal = Color(0xFFDA1000)

val secondaryNormal = Color(0xFF366EE3)

// Secondary
val secondary_light = Color(0xFFEBF1FC)
val secondary_light_hover = Color(0xFFE1E9FB)
val secondary_light_active = Color(0xFFC1D2F6)

val secondary_normal = Color(0xFF366EE3)
val secondary_normal_hover = Color(0xFF3163CC)
val secondary_normal_active = Color(0xFF2B58B6)
val secondary_dark = Color(0xFF2953AA)
val secondary_dark_hover = Color(0xFF204288)
val secondary_dark_active = Color(0xFF183166)
val secondary_darker = Color(0xFF13274F)

// Success
val success_light = Color(0xFFEDF7ED)
val success_light_hover = Color(0xFFE4F3E5)
val success_light_active = Color(0xFFC7E6C8)
val success_normal = Color(0xFF4BAE4F)
val success_normal_hover = Color(0xFF449D47)
val success_normal_active = Color(0xFF3C8B3F)
val success_dark = Color(0xFF38833B)
val success_dark_hover = Color(0xFF2D682F)
val success_dark_active = Color(0xFF224E24)
val success_darker = Color(0xFF1A3D1C)

// Error
val rust_red = Color(0xFFA94C45)
val pinkish_light = Color(0xFFF6EDEA)

val error_light = Color(0xFFFBE7E6)
val error_light_hover = Color(0xFFF9DBD9)
val error_light_active = Color(0xFFF4B5B0)
val error_normal = Color(0xFFDA1000)
val error_normal_hover = Color(0xFFC40E00)
val error_normal_active = Color(0xFFAE0D00)
val error_dark = Color(0xFFA40C00)
val error_dark_hover = Color(0xFF830A00)
val error_dark_active = Color(0xFF620700)
val error_darker = Color(0xFF4C0600)

// Yellow
val yellow_light = Color(0xFFFEF8E6)
val yellow_light_hover = Color(0xFFFDF5D9)
val yellow_light_active = Color(0xFFFCEAB0)
val yellow_normal = Color(0xFFF4BB00)
val yellow_normal_hover = Color(0xFFDCA800)
val yellow_normal_active = Color(0xFFC39600)
val yellow_dark = Color(0xFFB78C00)
val yellow_dark_hover = Color(0xFF927000)
val yellow_dark_active = Color(0xFF6E5400)
val yellow_darker = Color(0xFF554100)


// Black
val black_light = Color(0xFFE6E6E6)
val black_light_hover = Color(0xFFD9D9D9)
val black_light_active = Color(0xFFB0B0B0)
val black_normal = Color(0xFF000000)
val black_normal_hover = Color(0xFF000000)
val black_normal_active = Color(0xFF000000)
val black_dark = Color(0xFF000000)
val black_dark_hover = Color(0xFF000000)
val black_dark_active = Color(0xFF000000)
val black_darker = Color(0xFF000000)

// White
val white_light = Color(0xFFFFFFFF)
val white_light_hover = Color(0xFFFFFFFF)
val white_light_active = Color(0xFFFFFFFF)
val white_normal = Color(0xFFFFFFFF)
val white_normal_hover = Color(0xFFE6E6E6)
val white_normal_active = Color(0xFFCCCCCC)
val white_dark = Color(0xFFBFBFBF)
val white_dark_hover = Color(0xFF999999)
val white_dark_active = Color(0xFF737373)
val white_darker = Color(0xFF595959)

// Natural
val natural_light = Color(0xFFF4F4F5)
val natural_light_hover = Color(0xFFEFEEEF)
val natural_light_active = Color(0xFFDDDDDF)
val natural_normal = Color(0xFF919097)
val natural_normal_hover = Color(0xFF838288)
val natural_normal_active = Color(0xFF747379)
val natural_dark = Color(0xFF6D6C71)
val natural_dark_hover = Color(0xFF57565B)
val natural_dark_active = Color(0xFF414144)
val natural_darker = Color(0xFF333235)

// error_normal
val background_light = Color(0xFFFFFFFF)
val background_light_hover = Color(0xFFFFFFFF)
val background_light_active = Color(0xFFFFFFFF)
val background_normal = Color(0xFFFFFFFC)
val background_normal_hover = Color(0xFFE6E6E3)
val background_normal_active = Color(0xFFCCCCCA)
val background_dark = Color(0xFFBFBFBD)
val background_dark_hover = Color(0xFF999997)
val background_dark_active = Color(0xFF737371)
val background_darker = Color(0xFF595958)


// Status
val status_success_fill = Color(0xFF04B051)

// Orange
val orange_active = Color(0xFFFF7A00)
val orange_label = Color(0xFFFFF2E5)


// Theme builder generation
val primaryLight = Color(0xFF565992)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFE0E0FF)
val onPrimaryContainerLight = Color(0xFF11144B)
val secondaryLight = Color(0xFF5C5D72)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE1E0F9)
val onSecondaryContainerLight = Color(0xFF191A2C)
val tertiaryLight = Color(0xFF485D92)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFDAE2FF)
val onTertiaryContainerLight = Color(0xFF001847)
val errorLight = Color(0xFF904B3F)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD4)
val onErrorContainerLight = Color(0xFF3A0904)
val backgroundLight = Color(0xFFFBF8FF)
val onBackgroundLight = Color(0xFF1B1B21)
val surfaceLight = white_normal
val onSurfaceLight = Color(0xFF1B1B21)
val surfaceVariantLight = Color(0xFFE3E1EC)
val onSurfaceVariantLight = Color(0xFF46464F)
val outlineLight = Color(0xFF767680)
val outlineVariantLight = Color(0xFFC7C5D0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF303036)
val inverseOnSurfaceLight = Color(0xFFF2F0F7)
val inversePrimaryLight = Color(0xFFBFC2FF)
val surfaceDimLight = Color(0xFFDBD9E0)
val surfaceBrightLight = Color(0xFFFBF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF5F2FA)
val surfaceContainerLight = Color(0xFFEFEDF4)
val surfaceContainerHighLight = Color(0xFFE9E7EF)
val surfaceContainerHighestLight = Color(0xFFE3E1E9)

val primaryLightMediumContrast = Color(0xFF3A3E74)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF6C70AA)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF404155)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF727389)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF2C4174)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF5F73AA)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF6E3026)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFAA6053)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFBF8FF)
val onBackgroundLightMediumContrast = Color(0xFF1B1B21)
val surfaceLightMediumContrast = Color(0xFFFBF8FF)
val onSurfaceLightMediumContrast = Color(0xFF1B1B21)
val surfaceVariantLightMediumContrast = Color(0xFFE3E1EC)
val onSurfaceVariantLightMediumContrast = Color(0xFF42424B)
val outlineLightMediumContrast = Color(0xFF5E5E67)
val outlineVariantLightMediumContrast = Color(0xFF7A7A83)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF303036)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF2F0F7)
val inversePrimaryLightMediumContrast = Color(0xFFBFC2FF)
val surfaceDimLightMediumContrast = Color(0xFFDBD9E0)
val surfaceBrightLightMediumContrast = Color(0xFFFBF8FF)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF5F2FA)
val surfaceContainerLightMediumContrast = Color(0xFFEFEDF4)
val surfaceContainerHighLightMediumContrast = Color(0xFFE9E7EF)
val surfaceContainerHighestLightMediumContrast = Color(0xFFE3E1E9)

val primaryLightHighContrast = primary_normal
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF3A3E74)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = secondary_normal
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF404155)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF041F51)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF2C4174)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = error_normal
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF6E3026)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = background_normal
val onBackgroundLightHighContrast = Color(0xFF1B1B21)
val surfaceLightHighContrast = Color(0xFFFBF8FF)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFE3E1EC)
val onSurfaceVariantLightHighContrast = Color(0xFF23232B)
val outlineLightHighContrast = Color(0xFF42424B)
val outlineVariantLightHighContrast = Color(0xFF42424B)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF303036)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFECEAFF)
val surfaceDimLightHighContrast = Color(0xFFDBD9E0)
val surfaceBrightLightHighContrast = Color(0xFFFBF8FF)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF5F2FA)
val surfaceContainerLightHighContrast = Color(0xFFEFEDF4)
val surfaceContainerHighLightHighContrast = Color(0xFFE9E7EF)
val surfaceContainerHighestLightHighContrast = Color(0xFFE3E1E9)

val primaryDark = Color(0xFFBFC2FF)
val onPrimaryDark = Color(0xFF272B60)
val primaryContainerDark = Color(0xFF3E4278)
val onPrimaryContainerDark = Color(0xFFE0E0FF)
val secondaryDark = Color(0xFFC5C4DD)
val onSecondaryDark = Color(0xFF2E2F42)
val secondaryContainerDark = Color(0xFF444559)
val onSecondaryContainerDark = Color(0xFFE1E0F9)
val tertiaryDark = Color(0xFFB2C5FF)
val onTertiaryDark = Color(0xFF172E60)
val tertiaryContainerDark = Color(0xFF304578)
val onTertiaryContainerDark = Color(0xFFDAE2FF)
val errorDark = Color(0xFFFFB4A7)
val onErrorDark = Color(0xFF561E16)
val errorContainerDark = Color(0xFF73342A)
val onErrorContainerDark = Color(0xFFFFDAD4)
val backgroundDark = Color(0xFF131318)
val onBackgroundDark = Color(0xFFE4E1E9)
val surfaceDark = Color(0xFF121318)
val onSurfaceDark = Color(0xFFE3E1E9)
val surfaceVariantDark = Color(0xFF46464F)
val onSurfaceVariantDark = Color(0xFFC7C5D0)
val outlineDark = Color(0xFF90909A)
val outlineVariantDark = Color(0xFF46464F)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE3E1E9)
val inverseOnSurfaceDark = Color(0xFF303036)
val inversePrimaryDark = Color(0xFF565992)
val surfaceDimDark = Color(0xFF121318)
val surfaceBrightDark = Color(0xFF38393F)
val surfaceContainerLowestDark = Color(0xFF0D0E13)
val surfaceContainerLowDark = Color(0xFF1B1B21)
val surfaceContainerDark = Color(0xFF1F1F25)
val surfaceContainerHighDark = Color(0xFF292A2F)
val surfaceContainerHighestDark = Color(0xFF34343A)

val primaryDarkMediumContrast = Color(0xFFC4C6FF)
val onPrimaryDarkMediumContrast = Color(0xFF0B0E46)
val primaryContainerDarkMediumContrast = Color(0xFF888CC8)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFC9C9E1)
val onSecondaryDarkMediumContrast = Color(0xFF141526)
val secondaryContainerDarkMediumContrast = Color(0xFF8F8FA6)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFB8CAFF)
val onTertiaryDarkMediumContrast = Color(0xFF00143C)
val tertiaryContainerDarkMediumContrast = Color(0xFF7B8FC8)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAAE)
val onErrorDarkMediumContrast = Color(0xFF330502)
val errorContainerDarkMediumContrast = Color(0xFFCC7B6E)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF131318)
val onBackgroundDarkMediumContrast = Color(0xFFE4E1E9)
val surfaceDarkMediumContrast = Color(0xFF121318)
val onSurfaceDarkMediumContrast = Color(0xFFFDFAFF)
val surfaceVariantDarkMediumContrast = Color(0xFF46464F)
val onSurfaceVariantDarkMediumContrast = Color(0xFFCBC9D4)
val outlineDarkMediumContrast = Color(0xFFA3A2AC)
val outlineVariantDarkMediumContrast = Color(0xFF83828C)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE3E1E9)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF292A2F)
val inversePrimaryDarkMediumContrast = Color(0xFF3F437A)
val surfaceDimDarkMediumContrast = Color(0xFF121318)
val surfaceBrightDarkMediumContrast = Color(0xFF38393F)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF0D0E13)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1B1B21)
val surfaceContainerDarkMediumContrast = Color(0xFF1F1F25)
val surfaceContainerHighDarkMediumContrast = Color(0xFF292A2F)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF34343A)

val primaryDarkHighContrast = Color(0xFFFDF9FF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFC4C6FF)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFFDF9FF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFC9C9E1)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFFCFAFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFB8CAFF)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F8)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAAE)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF131318)
val onBackgroundDarkHighContrast = Color(0xFFE4E1E9)
val surfaceDarkHighContrast = Color(0xFF121318)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF46464F)
val onSurfaceVariantDarkHighContrast = Color(0xFFFDFAFF)
val outlineDarkHighContrast = Color(0xFFCBC9D4)
val outlineVariantDarkHighContrast = Color(0xFFCBC9D4)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE3E1E9)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF20245A)
val surfaceDimDarkHighContrast = Color(0xFF121318)
val surfaceBrightDarkHighContrast = Color(0xFF38393F)
val surfaceContainerLowestDarkHighContrast = Color(0xFF0D0E13)
val surfaceContainerLowDarkHighContrast = Color(0xFF1B1B21)
val surfaceContainerDarkHighContrast = Color(0xFF1F1F25)
val surfaceContainerHighDarkHighContrast = Color(0xFF292A2F)
val surfaceContainerHighestDarkHighContrast = Color(0xFF34343A)


val profileTabsTitleColor = Color(0xFF366EE3)
val profileTabsTitleColorGrey = Color(0xFF919097)
val profileInsuranceTitleColorGrey = Color(0xFF366EE3)
val pink = Color(0xFFFE5C5C)
val purple = Color(0xFF526ED3)
val greenStatus = Color(0xFF4BAE4F)
val yellowStatus = Color(0xFFF4BB00)
val blueStatus = Color(0xFF2383AC)
val transparentAppBar = Color(0x99FFFFFF)

val pearlyPurple = Color(0xFFBD65A4)
val selectiveYellow = Color(0XFFFCBB14)

val gainsBoro = Color(0xFFDDDDDF)


val lavenderBlushNormal = Color(0xFFBF66A4)
val lavenderBlushLight = Color(0xFFF2ECFB)


val coolGray = Color(0xFF919097)

